#!/usr/bin/env python2.7

import sys
import notmuch

db = notmuch.Database(mode=notmuch.Database.MODE.READ_WRITE)
limit_new = False

def inherit_tag(tag):
    q = 'tag:' + tag
    if limit_new:
        q += ' and tag:new'
    query = notmuch.Query(db, q)
    for thread in query.search_threads():
        for msg in thread.get_messages():
            msg.add_tag(tag)

if sys.argv[1] == '-new':
    limit_new = True
    tags = sys.argv[2:]
else:
    tags = sys.argv[1:]

for arg in tags:
    print 'inheriting tag', arg
    inherit_tag(arg)
